export const AuthActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_IN_PENDING: "SIGN_IN_PENDING",
  SIGN_IN_FULFILLED: "SIGN_IN_FULFILLED",

  SIGN_UP: "SIGN_UP",
  SIGN_UP_PENDING: "SIGN_UP_PENDING",
  SIGN_UP_FULFILLED: "SIGN_UP_FULFILLED"
};


export const HistoryActionTypes = {
    ADD_HISTORY: "ADD_HISTORY"
}