export const RecipeActionTypes = {
  GET_RECIPES_LIST: "GET_RECIPES_LIST",
  GET_RECIPE: 'GET_RECIPE',
  RECIPE_SELECTED: 'RECIPE_SELECTED',
  CLOSE_RECIPE_MODAL: 'CLOSE_RECIPE_MODAL'
  // GET_RECIPES_LIST_PENDING: "GET_RECIPES_LIST_PENDING",
  // GET_RECIPES_LIST_FULFILLED: "GET_RECIPES_LIST_FULFILLED",
};
