export const RecipeActionTypes = {

  GET_RECIPES_LIST: "GET_RECIPES_LIST",
  GET_RECIPES_LIST_PENDING: "GET_RECIPES_LIST_PENDING",
  GET_RECIPES_LIST_FULFILLED: "GET_RECIPES_LIST_FULFILLED",

  GET_MY_RECIPES_LIST: 'GET_MY_RECIPES_LIST',
  GET_MY_RECIPES_LIST_PENDING: 'GET_MY_RECIPES_LIST_PENDING',
  GET_MY_RECIPES_LIST_FULFILLED: 'GET_MY_RECIPES_LIST_FULFILLED',
  
  GET_RECIPE: 'GET_RECIPE',

  RECIPE_SELECTED: 'RECIPE_SELECTED',

  CLOSE_RECIPE_MODAL: 'CLOSE_RECIPE_MODAL',

  FILTER_RECIPE_LIST: 'FILTER_RECIPE_LIST',
  // GET_RECIPES_LIST_PENDING: "GET_RECIPES_LIST_PENDING",
  // GET_RECIPES_LIST_FULFILLED: "GET_RECIPES_LIST_FULFILLED",

  ADD_RECIPE: "ADD_RECIPE",
  ADD_RECIPE_PENDING: "ADD_RECIPE_PENDING",
  ADD_RECIPE_FULFILLED: "ADD_RECIPE_FULFILLED"
};
