export const IngredientsActionTypes = {
  GET_INGREDIENTS: "GET_INGREDIENTS",
  GET_INGREDIENTS_PENDING: "GET_INGREDIENTS_PENDING",
  GET_INGREDIENTS_FULFILLED: "GET_INGREDIENTS_FULFILLED",

  EDIT_INGREDIENT_CLICKED: "EDIT_INGREDIENT_CLICKED",

  ADD_INGREDIENT_CLICKED: "ADD_INGREDIENT_CLICKED",

  ADD_INGREDIENT: "ADD_INGREDIENT",
  ADD_INGREDIENT_PENDING: "ADD_INGREDIENT_PENDING",
  ADD_INGREDIENT_FULFILLED: "ADD_INGREDIENT_FULFILLED",

  UPDATE_INGREDIENT: "UPDATE_INGREDIENT",
  UPDATE_INGREDIENT_PENDING: "UPDATE_INGREDIENT_PENDING",
  UPDATE_INGREDIENT_FULFILLED: "UPDATE_INGREDIENT_FULFILLED",
  
  GET_INGREDIENT: "GET_INGREDIENT",

  CLOSE_INGREDIENT_MODAL: "CLOSE_INGREDIENT_MODAL"
};
