export const IngredientsActionTypes = {
  GET_INGREDIENTS: "GET_INGREDIENTS",
  GET_INGREDIENTS_PENDING: "GET_INGREDIENTS_PENDING",
  GET_INGREDIENTS_FULFILLED: "GET_INGREDIENTS_FULFILLED",

  GET_INGREDIENT: "GET_INGREDIENT",

  CLOSE_INGREDIENT_MODAL: "CLOSE_INGREDIENT_MODAL"
};
